export const admininfo=[{
    name: "Manager 1",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: 95,
    performance: "Metrics",
    id:0,
 

   },
   {
      
    name: "Manager 2",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Inactive",
    student: "95",
    performance: "Metrics",
    id:1,
   },
   {
    name: "Manager 3",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:2,
   },
   {
    name: "Manager 4",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:3,
   },
   {
    name: "Manager 5",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:4,
   },
   {
    name: "Manager 6",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:5,
   },
   {
    name: "Manager 7",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:6,
   },
   {
    name: "Manager 8",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:7,
   },
   {
    name: "Manager 9",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:8,
   },
   {
    name: "Manager 10",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:9,
   },
   {
    name: "Manager 11",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:10,
   },
   {
    name: "Manager 12",
    email: "ss@gmail.com",
    update: "02/02/2022",
    status: "Active",
    student: "95",
    performance: "Metrics",
    id:11.
   }]
